-- Survey Central -- import real employee roster (Organik + TAD/outsourcing)
-- extracted from HR PDF exports, reconciled against the existing org-chart.
-- Every row from both PDFs is now included: GM/Project Management, each
-- division's Division Head role, and units with no Department Head yet
-- (Finance Section, Airport Aeronautical, Support Services/PJP2U/HC
-- Solution) are all bucketed as their own Department-Head-equivalent leaf
-- under the "General Manager" group -- see orgStructure.js and chat
-- discussion. Run this AFTER 007.

begin;

-- New Department-Head-equivalent leaves that sit under "General Manager"
-- in orgStructure.js (division heads + units with no Department Head yet).
insert into departments (nama) values
  ('General Manager'),
  ('Airport Operation, Services & Security Division Head'),
  ('Airport Technical Division Head'),
  ('Airport Commercial Division Head'),
  ('Airport Quality & Safety Management System Division Head'),
  ('Finance Section'),
  ('Airport Aeronautical'),
  ('Support Services')
on conflict (nama) do nothing;

-- Remove the old placeholder/mock employees seeded in 003_seed_data.sql --
-- they have no real NIP and are being replaced by the real roster below.
-- (Historical submissions/notifications referencing these names by free-text
-- `nama` are left untouched; only the `employees` roster itself is replaced.)
delete from employees where nip is null;

-- Insert the real employee roster.
insert into employees (nip, nama, unit_kerja, jenis_pegawai) values
  ('20240705', 'Muhammad Thamrin', 'General Manager', 'Organik'),
  ('20241527', 'Ratih Rosini Komara', 'General Manager', 'Organik'),
  ('20240784', 'Chrismawan Andry Wibowo', 'General Manager', 'Organik'),
  ('20240294', 'Didik Hermanto', 'Airport Operation Center Head', 'Organik'),
  ('20240332', 'Mulyadi Suparjo', 'Airport Operation Center Head', 'Organik'),
  ('20240662', 'I Made Sumardika', 'Airport Operation Center Head', 'Organik'),
  ('20241558', 'Binsar Reynold', 'Airport Operation Center Head', 'Organik'),
  ('20243276', 'Nugroho Yoga Irawan', 'Airport Operation Center Head', 'Organik'),
  ('20244468', 'Hermawati Purwandari', 'Legal & Compliance Department Head', 'Organik'),
  ('20244283', 'Dian Ratih Ristauri', 'Legal & Compliance Department Head', 'Organik'),
  ('20243496', 'Andhi Wijaya', 'Legal & Compliance Department Head', 'Organik'),
  ('20242735', 'Rita Nawangsari Pamungkas', 'Airport Environment Department Head', 'Organik'),
  ('20241960', 'Moh Arif Wahyuliyanto', 'Airport Environment Department Head', 'Organik'),
  ('20240200', 'Rahmat Febrian Syahrani', 'Airport Operation, Services & Security Division Head', 'Organik'),
  ('20240722', 'Pri Arip Legowo', 'Airport Operation, Services & Security Division Head', 'Organik'),
  ('20241318', 'Danang Triyanto', 'Airport Operation, Services & Security Division Head', 'Organik'),
  ('20241366', 'M. Chafid Islahul Abid', 'Airport Operation, Services & Security Division Head', 'Organik'),
  ('20241418', 'Rahmat Riadi H.B.', 'Airport Operation, Services & Security Division Head', 'Organik'),
  ('20241415', 'Achmad Faruq', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241712', 'Danang Agung Wijayanto', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241735', 'Maryanto Muljo Suharto', 'Airport Operation Airside Department Head', 'Organik'),
  ('20240284', 'Widada', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241715', 'Sukmono Prakoso', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241717', 'Tulus Widiatmoko', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241718', 'Rewanghadi Widagdo', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241733', 'Devi Andri Putra', 'Airport Operation Airside Department Head', 'Organik'),
  ('20241739', 'Yahya Nopianto', 'Airport Operation Airside Department Head', 'Organik'),
  ('20242309', 'Risman Noermansyah', 'Airport Operation Airside Department Head', 'Organik'),
  ('20242657', 'Junnani Jumantoro', 'Airport Operation Airside Department Head', 'Organik'),
  ('20242675', 'Ritzqi Jati Wahyugi', 'Airport Operation Airside Department Head', 'Organik'),
  ('20244498', 'Ardian Daru', 'Airport Operation Airside Department Head', 'Organik'),
  ('20244563', 'Dominicus Argasari Candra Setyamurti', 'Airport Operation Airside Department Head', 'Organik'),
  ('20246224', 'Rusdian Permana', 'Airport Operation Airside Department Head', 'Organik'),
  ('20246536', 'Robith Basyarul Alam', 'Airport Operation Airside Department Head', 'Organik'),
  ('20246363', 'Asrul Sani', 'Airport Operation Airside Department Head', 'Organik'),
  ('20246428', 'Sonny Wiratama', 'Airport Operation Airside Department Head', 'Organik'),
  ('20246425', 'Ana Rasmayanti', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20242884', 'Fitri Kusumandari', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20242044', 'Yosi Amrina Rosidah', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20244167', 'Jepi Pardamean', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20244172', 'Doni Aji Nugroho', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20244195', 'Yunita Setia Utami', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20244573', 'Rizka Mutiara', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20246566', 'Aldony Nerroviisy', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20246394', 'Armi Damayanti', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20246574', 'Theodery Marliwanto Ranteala', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20247635', 'Danang Prasetya', 'Airport Operation Landside & Terminal Department Head', 'Organik'),
  ('20246187', 'I Gede Sastra Mahaesa', 'Airport Services Improvement Department Head', 'Organik'),
  ('20246107', 'Rafli Martias', 'Airport Services Improvement Department Head', 'Organik'),
  ('20246714', 'Eneng Feny Nuraeny', 'Airport Services Improvement Department Head', 'Organik'),
  ('20241338', 'Muhammad Oscar Avianto', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241347', 'Ghufran Riyadi', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241358', 'Endar Prasetyo', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241361', 'Ananta As''adhi', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241887', 'Hasar Fitrakusuma', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242153', 'Sukamto', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242169', 'Aris Hervinsa Yulianto', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241375', 'Ahmad Nizar Catur Prasetyo', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241884', 'Thomas Donny Supraptono', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241895', 'Hari Mukti Catur Pamungkas', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241907', 'Kukuh Prabowo Indriyatmoko', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241916', 'Maulana Malik Ibrahim', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241927', 'Ruliawan Halim', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241961', 'Dwi Rizky Widianto', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241970', 'Rudy Setyawan Pramana', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241992', 'Dony Setiawan', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242159', 'Wahyu Adhy Dwibowo', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242162', 'Ardian', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242176', 'Fajar Danymar Romdhoni', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20242421', 'Ibnu Juliyadi', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20244078', 'Danar Putra Daru', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20244540', 'Ahmad Abdul Fatih', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20244550', 'Apriliyanto Adi Supatma', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20245386', 'Diana Hery Setiawan', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20245563', 'Kukuh Tri Putranto', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246061', 'Johan Asep Setiono', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20245064', 'Nur Kholis', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246596', 'Sholikin Tri Nur Cahyo', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246631', 'Titus Dwi Prakoso', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246647', 'Paxianjas Wibisono', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246663', 'Bagoes Sukarno', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246710', 'Alif Damario Saesandy', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246212', 'Moh. Abdul Basyar', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20246214', 'Dimas Indra Kusuma', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241981', 'Frans Dwi Herdiansyah', 'Airport Security Protection Department Head', 'Organik'),
  ('20240049', 'Puji Suyono', 'Airport Security Protection Department Head', 'Organik'),
  ('20240440', 'Suko Raharjo', 'Airport Security Protection Department Head', 'Organik'),
  ('20241351', 'Dina Nurmaladewi', 'Airport Security Protection Department Head', 'Organik'),
  ('20241901', 'Dwi Andika Rochman', 'Airport Security Protection Department Head', 'Organik'),
  ('20241989', 'Hawing Yuliantoro', 'Airport Security Protection Department Head', 'Organik'),
  ('20242382', 'Didik Slamet Santoso', 'Airport Security Protection Department Head', 'Organik'),
  ('20241893', 'Defri Armanda Sulanggri', 'Airport Security Protection Department Head', 'Organik'),
  ('20247302', 'I Wayan Gede Dwi Adnyana Putra', 'Airport Security Protection Department Head', 'Organik'),
  ('20243980', 'Anggir Riyanto', 'Airport Security Protection Department Head', 'Organik'),
  ('20243986', 'Dedi Felani', 'Airport Security Protection Department Head', 'Organik'),
  ('20244469', 'Adittia Prasetyo', 'Airport Security Protection Department Head', 'Organik'),
  ('20246066', 'Dhistira Agung Pramana', 'Airport Security Protection Department Head', 'Organik'),
  ('20246330', 'Heri Kuncoro', 'Airport Security Protection Department Head', 'Organik'),
  ('20246605', 'Benny Rilo Pambudi', 'Airport Security Protection Department Head', 'Organik'),
  ('20246614', 'Muhammad Yudha Abdillah', 'Airport Security Protection Department Head', 'Organik'),
  ('20246682', 'Hawky Aryatama Sanjaya', 'Airport Security Protection Department Head', 'Organik'),
  ('20246707', 'Syahrozi', 'Airport Security Protection Department Head', 'Organik'),
  ('20240355', 'Kriswanto Hadi Wijaya', 'Airport Security Screening Department Head', 'Organik'),
  ('20240763', 'Arif Rahman', 'Airport Security Screening Department Head', 'Organik'),
  ('20241317', 'Qodariah Timorianti', 'Airport Security Screening Department Head', 'Organik'),
  ('20241339', 'Arik Candra Santoso', 'Airport Security Screening Department Head', 'Organik'),
  ('20241387', 'Dimas Budi Bintara Jaya', 'Airport Security Screening Department Head', 'Organik'),
  ('20241892', 'Wahyu Agus Lestiono', 'Airport Security Screening Department Head', 'Organik'),
  ('20241869', 'Roy Rhomadona', 'Airport Security Screening Department Head', 'Organik'),
  ('20247145', 'Ida Ayu Wika Widyastuti', 'Airport Security Screening Department Head', 'Organik'),
  ('20247149', 'Dwi Rahmani Ratih', 'Airport Security Screening Department Head', 'Organik'),
  ('20244003', 'Ismu Prasetya', 'Airport Security Screening Department Head', 'Organik'),
  ('20244014', 'Ardyn Nurrahmawan', 'Airport Security Screening Department Head', 'Organik'),
  ('20244042', 'Anna Wulandari', 'Airport Security Screening Department Head', 'Organik'),
  ('20244465', 'Diah Yulistia', 'Airport Security Screening Department Head', 'Organik'),
  ('20245230', 'Maulana Haryo Hardiyanto', 'Airport Security Screening Department Head', 'Organik'),
  ('20244011', 'Haryono', 'Airport Security Screening Department Head', 'Organik'),
  ('20244456', 'Adin Vita Jati Maulani', 'Airport Security Screening Department Head', 'Organik'),
  ('20244480', 'Yudhanto Andhi Handoko', 'Airport Security Screening Department Head', 'Organik'),
  ('20245109', 'Arda Pradana', 'Airport Security Screening Department Head', 'Organik'),
  ('20246383', 'Ponco Achmad Nur Rohim', 'Airport Security Screening Department Head', 'Organik'),
  ('20246451', 'Lintang Giri Budinata', 'Airport Security Screening Department Head', 'Organik'),
  ('20246589', 'Kamelia', 'Airport Security Screening Department Head', 'Organik'),
  ('20246709', 'Nia Agustina', 'Airport Security Screening Department Head', 'Organik'),
  ('20240657', 'Tamsul Sadikin', 'Airport Rescue & Fire Fighting Department Head', 'Organik'),
  ('20241756', 'Eddy Syamsul B', 'Airport Technical Division Head', 'Organik'),
  ('20244342', 'Dika Arwinda Sulviari', 'Airport Facilities Department Head', 'Organik'),
  ('20246125', 'Adithya Maulana Arifin', 'Airport Facilities Department Head', 'Organik'),
  ('20242774', 'Novita Robby Sartika', 'Airport Facilities Department Head', 'Organik'),
  ('20246225', 'Rahmat Bungo Simamora', 'Airport Facilities Department Head', 'Organik'),
  ('20244389', 'Hannif Ariasto Raharjo', 'Airport Facilities Department Head', 'Organik'),
  ('20246463', 'Aldila Kurnia', 'Airport Facilities Department Head', 'Organik'),
  ('20242008', 'Thursina Mistika', 'Airport Equipment Department Head', 'Organik'),
  ('20241593', 'Herumantoro', 'Airport Equipment Department Head', 'Organik'),
  ('20243022', 'Dimas Suyaksya', 'Airport Equipment Department Head', 'Organik'),
  ('20242022', 'Muhammad Fadly', 'Airport Equipment Department Head', 'Organik'),
  ('20243010', 'Mu''awanah', 'Airport Equipment Department Head', 'Organik'),
  ('20244214', 'Agung Raya Tofa', 'Airport Equipment Department Head', 'Organik'),
  ('20244234', 'Miranti Insi Auly Dewi', 'Airport Equipment Department Head', 'Organik'),
  ('20242302', 'Feby Hidayat Tullah', 'Airport Equipment Department Head', 'Organik'),
  ('20244294', 'Ersan Wijayanto', 'Airport Equipment Department Head', 'Organik'),
  ('20244340', 'Wahyu Hidayat', 'Airport Equipment Department Head', 'Organik'),
  ('20244554', 'Eka Priyana', 'Airport Equipment Department Head', 'Organik'),
  ('20246227', 'Rendi Bambang Prasetyo', 'Airport Equipment Department Head', 'Organik'),
  ('20246229', 'Muhammad Arif Wicaksono', 'Airport Equipment Department Head', 'Organik'),
  ('20246233', 'Wisnu Widayat', 'Airport Equipment Department Head', 'Organik'),
  ('20246248', 'Naufal Ibnul Roi''f Damran', 'Airport Equipment Department Head', 'Organik'),
  ('20241758', 'Herman Prayitno', 'Airport Technology Department Head', 'Organik'),
  ('20241560', 'Budhy Wahyu Isnantoro', 'Airport Technology Department Head', 'Organik'),
  ('20241629', 'Muh. Yusep Nugraha', 'Airport Technology Department Head', 'Organik'),
  ('20243020', 'Nurul Mukharomah', 'Airport Technology Department Head', 'Organik'),
  ('20244320', 'Rizky Ichsan Parama Putra', 'Airport Technology Department Head', 'Organik'),
  ('20246171', 'Luqman Hakim', 'Airport Technology Department Head', 'Organik'),
  ('20242055', 'Muh. Hatta Hidayatullah', 'Airport Technology Department Head', 'Organik'),
  ('20243012', 'Yondha Agung Prasetyo', 'Airport Technology Department Head', 'Organik'),
  ('20246528', 'Mukhamad Erwin Zakariya Kurniawan', 'Airport Technology Department Head', 'Organik'),
  ('20240627', 'Jarot Handoko', 'Airport Commercial Division Head', 'Organik'),
  ('20244287', 'Khairunnisa Indah Ningrum', 'Aero Commercial Department Head', 'Organik'),
  ('20240505', 'Erina Armelia Septianti', 'Aero Commercial Department Head', 'Organik'),
  ('20240615', 'Fitri Ardiani', 'Aero Commercial Department Head', 'Organik'),
  ('20246207', 'Daniel Yehezkiel Marlamb Putra', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20240513', 'Wendry Haryono Muhammad K', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20241241', 'R. Andriani', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20241249', 'Wulan Anggraeni', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20246147', 'Ninggar Seganten', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20247834', 'Raisa Abid Al Aziz', 'Non-Aero Commercial Department Head', 'Organik'),
  ('20240222', 'Anita Herawati', 'Branch Communication & CSR Department Head', 'Organik'),
  ('20244363', 'Afuah Sulistyowati', 'Branch Communication & CSR Department Head', 'Organik'),
  ('20246105', 'Ganes Nirwina Parapat Sari', 'Branch Communication & CSR Department Head', 'Organik'),
  ('20246537', 'Faizal Ramdani', 'Branch Communication & CSR Department Head', 'Organik'),
  ('20246584', 'Riska Ayu Ning Tyas', 'Branch Communication & CSR Department Head', 'Organik'),
  ('20241243', 'Yuliana Christina Endang P', 'Asset Management & General Services Department Head', 'Organik'),
  ('20241594', 'Prihati Muji Lestari', 'Asset Management & General Services Department Head', 'Organik'),
  ('20240479', 'Samhita Danarti Cahyawati', 'Asset Management & General Services Department Head', 'Organik'),
  ('20246349', 'Yohanis Rumlus Lewokerore Hering', 'Asset Management & General Services Department Head', 'Organik'),
  ('20241031', 'Indra Fandy Parlaungan Nasution', 'Airport Quality & Safety Management System Division Head', 'Organik'),
  ('20244250', 'Anang Eko Pribadi', 'Safety Management System & OHS Department Head', 'Organik'),
  ('20244460', 'Nurdiyanto', 'Safety Management System & OHS Department Head', 'Organik'),
  ('20241423', 'Verika Fitri Andriana', 'Airport Quality Control Department Head', 'Organik'),
  ('20247805', 'Shafira Balqis', 'Airport Quality Control Department Head', 'Organik'),
  ('2407100', 'Prita Budiningsih', 'Finance Section', 'Non-Organik'),
  ('2202269', 'Matheas Minardi S', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2407103', 'Putri Rizka Dewi Linda', 'General Manager', 'Non-Organik'),
  ('2403690', 'Fachry Haji Makkiyah', 'Safety Management System & OHS Department Head', 'Non-Organik'),
  ('2500890', 'Eky Allif Viyanto', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2403587', 'Wulan Damayanti', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2407109', 'Raselin Inge Juanita', 'Airport Aeronautical', 'Non-Organik'),
  ('2407137', 'Tonny Setya Nugraha', 'Airport Aeronautical', 'Non-Organik'),
  ('2202278', 'Novan Fajar Saktya', 'Airport Aeronautical', 'Non-Organik'),
  ('2202268', 'Martika Agustina', 'Airport Aeronautical', 'Non-Organik'),
  ('2301459', 'Irvani Cahyo Utomo', 'Airport Aeronautical', 'Non-Organik'),
  ('2202308', 'Setyo Wibowo', 'Airport Aeronautical', 'Non-Organik'),
  ('2407008', 'Adhika Satya Wicaksana', 'Airport Aeronautical', 'Non-Organik'),
  ('2405330', 'Ginanjar Wahyu Kuncoro', 'Airport Aeronautical', 'Non-Organik'),
  ('2301457', 'Muhammad Wali Al-Ckhalidy', 'Airport Aeronautical', 'Non-Organik'),
  ('2405328', 'Iwan Rifai', 'Airport Aeronautical', 'Non-Organik'),
  ('2210402', 'Nadika Raras Swadesi', 'Airport Aeronautical', 'Non-Organik'),
  ('2202082', 'Nur Amin Baharsyah', 'Airport Aeronautical', 'Non-Organik'),
  ('2209690', 'Ronal Suryana', 'Airport Aeronautical', 'Non-Organik'),
  ('2407134', 'Tavik Nurcahya', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2501836', 'Choiruman Miftah Nurhadi', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2407123', 'Sugiono', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2406037', 'Abriansyah Bima Nugraha', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2403680', 'Aditya Hendrawan Fanisaputra', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2202287', 'Prisma Al Muzaqin', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2501865', 'Luthfi Ristyawan Hanif', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2501842', 'Khoirun Saputra', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2403588', 'Y Bagas Indrawan', 'Airport Equipment Department Head', 'Non-Organik'),
  ('2407133', 'Taufiq Okta Fauzan', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2202332', 'Y. Agung Purnomo', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2202230', 'Doni Hidayat', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2202297', 'Ridi Sahana', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2407061', 'Is Byantoro', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2300981', 'Bani Aldrian', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2300982', 'Bintoro Laksono', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2300983', 'Widi Anggarani', 'Airport Facilities Department Head', 'Non-Organik'),
  ('2403694', 'M Alqi Nurfuadi', 'Airport Technology Department Head', 'Non-Organik'),
  ('2404101', 'Deby Setyanto', 'Airport Technology Department Head', 'Non-Organik'),
  ('2407116', 'Rizki Kurniawan Dwi Jadmika Putra', 'Airport Technology Department Head', 'Non-Organik'),
  ('2407075', 'Made Teguh Pranata Wibawa', 'Airport Technology Department Head', 'Non-Organik'),
  ('2407148', 'Yuldi Satria Sukmana', 'Airport Technology Department Head', 'Non-Organik'),
  ('2403699', 'Panji Dwi Sanjaya', 'Airport Technology Department Head', 'Non-Organik'),
  ('2501847', 'Rizqi Hasanuddin', 'Airport Technology Department Head', 'Non-Organik'),
  ('2202242', 'Fauzan Dwi Anandha Luthfi', 'Airport Technology Department Head', 'Non-Organik'),
  ('2403687', 'Chiputra Wahyu Aji', 'Airport Technology Department Head', 'Non-Organik'),
  ('2500891', 'Erwimansyah Tyass Kusuma', 'Airport Technology Department Head', 'Non-Organik'),
  ('2403701', 'Wahyu Widabudiatma', 'Airport Technology Department Head', 'Non-Organik'),
  ('2210010', 'Norman Ramadhan', 'Airport Technology Department Head', 'Non-Organik'),
  ('2403627', 'Muh Asrofi', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403624', 'Aryanto', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403625', 'Didik Purwanto', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403631', 'Ruliff Wahyu Sabian', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403630', 'Rony Suharjo', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403621', 'Alip Anggit Prasetiyo', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403628', 'Niva Anjas Permana', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403629', 'Reza Saputra Aditya', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('1902305', 'Andi Wihandoko', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403632', 'Rusydina Habibati', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403626', 'Isnain Al Fikri', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403622', 'Anggit Yoga Karsadi', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403623', 'Antok Muhfiarto', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403584', 'Muhammad Gibran Ghifari', 'Airport Operation Airside Department Head', 'Non-Organik'),
  ('2403696', 'Nabila Priandewi', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2202275', 'Muhtadi Yazid Shafly', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403695', 'Muhammad Fikri Zhaelani', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403697', 'Novikasari', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403686', 'Chandra Christian Vieri', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403688', 'Duta Prasetya Wibowo', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403681', 'Agung Budi Luhur Wibowo', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2407025', 'Arie Pradetya', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2202338', 'Yuliantoro Fitriawan', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2500869', 'Erich Fitriawan', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2403682', 'Almira Ma''rifati Robiah', 'Airport Operation Landside & Terminal Department Head', 'Non-Organik'),
  ('2501851', 'Aditya Gilang Pangestu Nugroho', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2407115', 'Riyono Sulistyo', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403634', 'Angga Satria Wicakso', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403644', 'Fitriana Ghaniy Mulyanto', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403641', 'Erwin Nur Hendrajaya', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403649', 'Retama Agung Rinaldhi', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403637', 'Bongga Zunianta', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403639', 'Diki Prihatin', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403640', 'Duwi Atmaji', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501856', 'Dedi Saputro', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501860', 'Syaiful Bayu Laksitoaji', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403642', 'Faiz Rafiqi', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403636', 'Bayu Chairul Nazmi Batubara', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403651', 'Shodiq Arifudin', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403653', 'Wiseno Aji', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403638', 'Danang Budiyantoro', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403633', 'Adika Prasetiya', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403647', 'Oktiano Rachman Saleh', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403648', 'Purwoto Sri Aji Pandoyo', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403650', 'Satria Bagas Pangestu', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501857', 'Fajar Hermawan', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403654', 'Yuna Priyana', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403645', 'Muh. Rizki Ramadhani P.F.', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501855', 'Danang Arfiansyach', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501859', 'Muhammad Bagas Sayuti', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2202331', 'Wisnu Pamungkas', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403643', 'Fariz Wisnu Qoirudin', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2304059', 'Titok Yulianto', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403646', 'Muhammad Guruh Batubara', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403652', 'Wahyu Krisnanto Eka Putra', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2407021', 'Anggi Hanindrajat', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2300023', 'Dwi Prianggono', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2300022', 'Dedy Mahardika', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2208693', 'Bangkit Alviyanto', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2208698', 'Muhammad Ikhsanudin', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2208700', 'Nana Mulyana', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2208701', 'Oka Ampran Gumilang', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2403586', 'Tegar Dimas Adi Pangestu', 'Airport Rescue & Fire Fighting Department Head', 'Non-Organik'),
  ('2501837', 'Ervin', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403667', 'Galih Riadi', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403669', 'Heriyanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2301456', 'Arif Budi Zakaria', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407111', 'Riky Doner Edgar Damara', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501849', 'Sidiq Rachman', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407097', 'Prasetyo Wijanarko', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202296', 'Riang Putra Utama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407152', 'Zainurrokhim', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501841', 'James Philar Dananjaya', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500902', 'Vina Apriyani', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500886', 'Dhimas Prasetyo Suryondaru', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407034', 'Chandra Diky Indrayanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501848', 'Sarif Purnama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2304364', 'Gayuh Dwisakti Kurnianto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407126', 'Sumistar', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407051', 'Febriarto Malik Alkarim', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500904', 'Wuryani', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2302565', 'Muhammad Irfan', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500897', 'Nuria Wulan Sari', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500884', 'David Putrananta', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500903', 'Wahyu Parasamya', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407033', 'Bramantyo Baskoro', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403663', 'Eko Priyo Prabowo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501845', 'Ngatijo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500900', 'Riyadi Pramono', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403677', 'Tri Edi Santoso', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500894', 'Indra Arfa Rimawan', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407092', 'Oni Suryono', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407026', 'Arista Putri Windarningsih', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403668', 'Herbangun Suwisma', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500887', 'Dicky Satriya Setiyawan', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407072', 'Kossa Dean Jerry Pratama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403673', 'Muhammad Prasetyo Bayu Adji', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500885', 'Deny Fardana Saputra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2304057', 'Irvan Yuliantoro', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2304365', 'Dwi Prasetya', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501840', 'Hari Purwantoro', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2404935', 'Sahrul Gunawan', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407049', 'Fadli Nurohman Wakhid', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501833', 'Ali Usman', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407043', 'Eko Budi Nugroho', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501830', 'Aditya Darmawan', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501850', 'Wisnu Saputro', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2303278', 'Avent Anfaza Noor', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407066', 'Joko Dwi Atmaji', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500881', 'Agus Sunarto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2402016', 'Bagus Prabowo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500882', 'Arditiya Yoga Pratama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403655', 'Anggit Prabawa Guratama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407084', 'Muhammad Syafiil Huda', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501839', 'Ferry Aryandi Ervianto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403672', 'Mimbar Arum Purbawinata', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2301455', 'Firmansyah', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407083', 'Muhammad Fatkurrohman', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407132', 'Taufik Yunus', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407113', 'Ritko Edi Triamanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407118', 'Septian Adi Putra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403664', 'Faizal Rofiq Romadhoni', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2210217', 'Arifian Jihad Putranto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2210403', 'Guntur Adhi Nugroho', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2301452', 'Arga Sugiarto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2406044', 'Mega Krisna Hidayat', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407102', 'Putra Dwi Santoso', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202208', 'Arif Khalil Al Patah', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2300851', 'Ramadhan Ebri Bagus Pratama', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2403678', 'Yosua Krissantono', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202228', 'Disdian Sandiaka', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407057', 'Heri Supriyanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2500883', 'Augusta Yudo Indrianto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202229', 'Dodi Ariesta Kusuma Wardana', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2301451', 'Muhammad Iqbal', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407071', 'Kiki Yahya Saputra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407007', 'Achmad Ryo Wahyudi', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407012', 'Agus Adi Saputra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407093', 'Pambudi Sasangka Aji', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407015', 'Aldi Budiman', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407096', 'Pradipta Indra Putra Wibowo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407041', 'Dwi Iryanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407145', 'Wiji Purnomo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202235', 'Eko Prasetiyo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407070', 'Joko Suprastyo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407031', 'Bayu Rahmanto', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2202217', 'Bayu Ridho Fawzi', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407104', 'Putut Hatmojo', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407147', 'Yan Sonaval Saputra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2407081', 'Muh Imran', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2208703', 'Agrita Parama Yudha', 'Branch Communication & CSR Department Head', 'Non-Organik'),
  ('2301000', 'Miwa Handayani', 'Branch Communication & CSR Department Head', 'Non-Organik'),
  ('2405329', 'Riza Yoaniza', 'Finance Section', 'Non-Organik'),
  ('2407048', 'Esti Wulansari', 'Finance Section', 'Non-Organik'),
  ('2301458', 'Indah Puspitasari', 'Finance Section', 'Non-Organik'),
  ('2407039', 'Diprita Cantika Ananda', 'Finance Section', 'Non-Organik'),
  ('2406731', 'Sunardi', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2500901', 'Sigit Putro Santoso', 'General Manager', 'Non-Organik'),
  ('2209694', 'Candra Achmad Pria Pandega', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2101769', 'Asri Wibowo', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2603260', 'Setyo Pramudyanto', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2501852', 'Andy Haryanto', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2503698', 'Ibnu Sudrajad', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2503697', 'Jemi Restian', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2202213', 'B. Krismaryadi', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2202284', 'Patriot Candra Purnama', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2407013', 'Agus Triyanto', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2208686', 'Muhammad Araj Wima Ajie', 'Asset Management & General Services Department Head', 'Non-Organik'),
  ('2210009', 'Wahyuni Setyo Dewi', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2407046', 'Engga Septingtyas', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403684', 'Bayu Isdiyanto', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403685', 'Brigita Arum Tyas Putantri', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403700', 'Panji Pamungkas', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403692', 'Indah Putri Setyaningrum', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403683', 'Aryadinata', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403702', 'Wibisono Pangestu', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403691', 'Firman Dhany', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2202222', 'Dedy Saputra Dwi Kusuma', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2405649', 'Naya Ardhya Santiko', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2407128', 'Susanti', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403698', 'Nugratama Pramudya Wardana', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2304056', 'Taufiqurahman Ramadhani Pamungkas', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403581', 'Dwi Novri', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403582', 'Kirani Difa Harista Qolbi', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('8250522', 'Briga Agusta Andaru', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2403585', 'Natalia Ananta', 'Airport Services Improvement Department Head', 'Non-Organik'),
  ('2208687', 'Nur Wahyudi', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2300977', 'Maulana Agwar Dwiputra', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2502522', 'Daffa Maulana Rivanny', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2210218', 'Muhamat Lanang Maulana', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2300976', 'Alif Imam Sholihin', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2501835', 'Bekti Dwi Wicaksono', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500888', 'Dika Anindita Ramadhani', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300849', 'Danang Setyawan Prakoso', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403675', 'Reza Firmansyah', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407091', 'Oktoberiandy', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501838', 'Evi Mayasari', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403660', 'Deddy Kurniawan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2402806', 'Yuda Wira Kusuma', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501843', 'Mirnawati', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403676', 'Siti Apsoh', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500889', 'Dodyd Irsyad Rafif', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500892', 'Fitri Ana Astuti', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403657', 'Arif Catur Swantoro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2105562', 'Zulfikar Awaluddin', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407047', 'Erastus Eldy Lenardo Cahyo Kumoro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407135', 'Theresia Latri Utami', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403656', 'Aprilia Alfionita', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403658', 'Arif Dwi Irfanto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500896', 'Muhammad Dikie Marhiendra Putra', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407143', 'Wenda Zelyca Racma', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407027', 'Arya Adi Prasetiya', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501844', 'Muizatul Hasanah', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501846', 'Nindia Mukti Wulansari', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403659', 'Arif Hermawan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501831', 'Afifah Khoiriyani', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407032', 'Birzha Khafitdalloh', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403276', 'Fakassin Kuluqi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500898', 'Patrick Tegar Rengga Rapusta', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501834', 'Arhan Fauzianto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403662', 'Edy Santoso', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407010', 'Adnan Aries Wimatama', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403661', 'Dina Mawalia Puspitaningrum', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2502521', 'Nur Iksan Yulia', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2502523', 'Muhammad Zidan Aqila Ratmera', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300978', 'Ryan Rizky Setyawan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300979', 'Diki Adi Sanjaya', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300980', 'Nasrodin', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2302564', 'Devi Setia Sari', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2208688', 'Rizki Subekti', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2208689', 'Tri Yoga Baskoro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2411024', 'Aditya Pamungkas', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2411023', 'Ayu Tri Widiyastuti', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407038', 'Didik Triantoro Isbiantoko', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500899', 'Raden Ilham Muhammad Farijd', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403674', 'Murdiantoro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500893', 'Hestian Agung Prayoga', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403679', 'Zainal Abidin', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403671', 'Miftakul Anam', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403666', 'Fuad Dewa Ramdhani', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407149', 'Yosanda Viyo Badiyaningrum', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407022', 'Annisa Fauziyah', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407150', 'Yuli Astutik', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407105', 'Rachmat Senati Wicaksono', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407141', 'Wahyu Kusbiyanto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2406408', 'Anggara Dika Montana', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407106', 'Rahardhian Wibawa Putra', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2500895', 'Miftakhul Amin', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407119', 'Sinto Hariyo Yudanto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2406414', 'Lugas Manggala Widigda Erlangga', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2403277', 'Novianto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407076', 'Mahmud Ireng Ismanto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2208690', 'Unggul Fadhil Muhammad', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300984', 'Vina Adinda Rohmadiyani', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2300850', 'Richy Effendi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2301876', 'Kukuh Rian Kurniawan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202251', 'I Nyoman Yudana Dharma Githa', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407080', 'Muchamad Isa Alamsyah Syahlan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407101', 'Purna Anang Prayogi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407074', 'Lutfi Edy Susanto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202325', 'Tri Septi Cahyo Wibisono', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407117', 'Satria Ari Wibawa', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202215', 'Bayu Irawan Saputra', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407069', 'Joko Siswadi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2501864', 'Ahmad Qaharur Rijal', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407029', 'Bagus Purhito', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202304', 'Rudi Setiawan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2402807', 'Juli Dwi Wijaya', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407110', 'Rifky Faisal Riandy', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407028', 'Aslama Addinul Hasan', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407037', 'Dhanur Febianto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407017', 'Ana Dwi Astuti', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407140', 'Wahyu Fajar Cahyana', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407129', 'Sutarjo', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407130', 'Suwardi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407063', 'Islakhul Asror', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407056', 'Herdinawan Siringoringo', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407079', 'Morgan Lucky Atmaja', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407127', 'Sunarto', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407058', 'Heroes Septima', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407062', 'Iskak Muhroji', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407045', 'Eko Saputro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407114', 'Rixy Bagaskara', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202290', 'Purnama', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407023', 'Ardhian Wibowo', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407042', 'Ega Bayu Adi Pratama', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407131', 'Tanjung Marta Sari', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407086', 'Ni Luh Dessy Kusumawati', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407077', 'Mardian Jimi Utomo', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407089', 'Norma Dwi Titisavi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407146', 'Winarni', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407055', 'Heni Heryanti', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2303493', 'Fajar Alfian Mawardi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407064', 'Istiningsih', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407054', 'Haryadi', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407073', 'Kukuh Galant Apriano', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407125', 'Sumantri', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407009', 'Aditya Warman', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2407120', 'Sodik Joko Purnomo', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2202232', 'Dwi Latri Sutoro', 'Airport Security Screening Department Head', 'Non-Organik'),
  ('2503700', 'Rafdi Fitra Riza', 'Airport Security Protection Department Head', 'Non-Organik'),
  ('2504521', 'Putry Ramanda Sani', 'Support Services', 'Non-Organik'),
  ('2504515', 'Finisia Pristika', 'Support Services', 'Non-Organik'),
  ('2504516', 'Nining Riawati', 'Support Services', 'Non-Organik'),
  ('2504517', 'Panca Putri Hikmawati', 'Support Services', 'Non-Organik'),
  ('2504518', 'Rahmat Hidayat', 'Support Services', 'Non-Organik'),
  ('2500868', 'Kinanti Swari Kitara', 'Support Services', 'Non-Organik')
on conflict (nama) do update set nip = excluded.nip, unit_kerja = excluded.unit_kerja, jenis_pegawai = excluded.jenis_pegawai;

commit;
